# Generated by Django 3.1.5 on 2021-01-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(default=0),
        ),
    ]
