# Generated by Django 3.1.5 on 2021-01-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=1400, verbose_name='Caption'),
        ),
    ]
